web/router.ex
defmodule Login.Router do
  use Login.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :browser_session do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Login do
    pipe_through [:browser, :browser_session]

    get "/", PageController, :index
    get "/registro", LoginController, :registro
    post "/registro", LoginController, :post_registro
    get "/login", LoginController, :login
    post "/login", LoginController, :post_login
    get "/logout", LoginController , :logout
  end

  # Other scopes may use custom stacks.
  # scope "/api", Login do
  #   pipe_through :api
  # end
end

lib/login/endpoint.ex
defmodule Login.Endpoint do
  use Phoenix.Endpoint, otp_app: :login

  socket "/socket", Login.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :login, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_login_key",
    signing_salt: "U0Q/YLjl"

  plug Login.Router
end

lib/login/repo.ex
defmodule Login.Repo do
  use Ecto.Repo, otp_app: :login
end

web/models/user.ex
defmodule Login.User do
  use Login.Web, :model
  import Comeonin.Bcrypt, only: [checkpw: 2, dummy_checkpw: 0, hashpwsalt: 1]

  schema "users" do
    field :email, :string
    field :password_encriptado, :string
    field :password, :string, virtual: true

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> changeset_new(params)
    |> encriptar
  end

  def changeset_new(struct, params \\ %{}) do
    struct
    |> cast(params, [:email, :password])
    |> validate_required([:email, :password])
    |> validate_length(:password, min: 7)
  end

  defp encriptar(%Ecto.Changeset{valid?: true, changes: %{password: pass}} = changeset) do
      changeset
        |> put_change(:password_encriptado, hashpwsalt(pass))
  end

  defp encriptar(changeset) do
    changeset
  end

  def validate_login(struct, params) do
    struct
    |> changeset_new(params)
    |> do_validate_login
  end

  defp do_validate_login(%Ecto.Changeset{valid?: false} = changeset) do
    IO.inspect changeset
    {:error, changeset}

  end

  defp do_validate_login(%Ecto.Changeset{valid?: true, changes: %{email: email, password: pass}} = changeset) do
    Login.Repo.get_by(Login.User, email: email)
      |> existe_usuario?(changeset, pass)
  end

  defp existe_usuario?(nil, changeset, _pass) do
    {:error, changeset |> add_error(:email, "No existe el usuario")}
  end

  defp existe_usuario?(%Login.User{} = user, changeset, passw) do
    checkpw(passw, user.password_encriptado)
    |> verificar_password(user, changeset)
  end

  defp verificar_password(true, user, _changeset) do
    {:ok, user}
  end

  defp verificar_password(false, _user, changeset) do
    dummy_checkpw()
    {:error, changeset |> add_error(:password, "Tu no eres tu")}
  end
end

web/controllers/login_controller.ex
defmodule Login.LoginController do
  use Login.Web, :controller
  alias Login.User

  def registro(conn, _params) do
    changeset = %User{} |> User.changeset_new()
    render conn, "registro.html", changeset: changeset
  end

  def post_registro(conn, %{"user" => user_params}) do
    changeset = %User{} |> User.changeset(user_params)
    case Repo.insert(changeset) do
        {:ok, user} ->
          conn
          |> Guardian.Plug.sign_in(user, :token)
          |> put_flash(:info, "Exito al registrarse.")
          |> redirect(to: page_path(conn, :index))
        {:error, changeset} ->
          render conn, "registro.html", changeset: changeset
    end
  end

  def logout(conn, _params) do
    conn
      |> Guardian.Plug.sign_out
      |> put_flash(:info, "Exito al desloguearse.")
      |> redirect(to: page_path(conn, :index))
  end

  def login(conn, _params) do
    changeset = %User{} |> User.changeset_new()
    render conn, "login.html", changeset: changeset
  end

  def post_login(conn, %{"user" => user_params}) do
    valid? = %User{} |> User.validate_login(user_params)
    case valid? do
        {:ok, user} ->
          conn
          |> Guardian.Plug.sign_in(user, :token)
          |> put_flash(:info, "Exito al registrarse.")
          |> redirect(to: page_path(conn, :index))
        {:error, changeset} ->
          render conn, "login.html", changeset: changeset
    end
  end
end

web/controllers/page_controller.ex
defmodule Login.PageController do
  use Login.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/views/error_view.ex
defmodule Login.ErrorView do
  use Login.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule Login.LayoutView do
  use Login.Web, :view

  def login?(conn) do
    Guardian.Plug.authenticated?(conn)
    |> render?(conn)
  end

  defp render?(false, conn) do
    render "login.html", conn: conn
  end

  defp render?(true, conn) do
    render "logout.html", conn: conn
  end
end

web/views/login_view.ex
defmodule Login.LoginView do
  use Login.Web, :view

end

web/views/page_view.ex
defmodule Login.PageView do
  use Login.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Login!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <%= login?(@conn) %>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/layout/login.html.eex
<li><%= link "Login", to: login_path(@conn, :login) %></li>

web/templates/layout/logout.html.eex
<li><%= link "Logout", to: login_path(@conn, :logout) %></li>

web/templates/login/login.html.eex
<h2>Login</h2>
<%= form_for @changeset, login_path(@conn, :post_login), fn f -> %>
  <div class="form_class">
    <%= label f, :email%>
    <%= email_input f, :email%>
    <%= error_tag f, :email %>
  </div>

  <div class="form_class">
    <%= label f, :password%>
    <%= password_input f, :password %>
    <%= error_tag f, :password %>
  </div>

  <%= submit "Login", class: "btn btn-success" %>

<% end %>

web/templates/login/registro.html.eex
<h2>Registro</h2>
<%= form_for @changeset, login_path(@conn, :post_registro), fn f -> %>
  <div class="form_class">
    <%= label f, :email%>
    <%= email_input f, :email%>
    <%= error_tag f, :email %>
  </div>

  <div class="form_class">
    <%= label f, :password%>
    <%= password_input f, :password %>
    <%= error_tag f, :password %>
  </div>

  <%= submit "Registrarse", class: "btn btn-success" %>

<% end %>

web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}", name: "Phoenix!" %></h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="https://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>